### ISSUE TITLE
[Request] GLPI 9.3 compatibility

### ISSUE THREAD

**Issue by iPaulis** [pluginsGLPI/room#31]
They have just released GLPI 9.3 beta and I don't know if this might break compatibility with the current plugin version.
Please, would you update the plugin to support GLPI 9.3 in its final stable version?

Thank you in advance.

**Comment by Stoatwblr** [comment]
+1 on this (if you don't have time to work on it, an estimate of when you might do will make most people happy)

**Comment by C-Duv** [comment]
Good news: I'm working on it right now.

**Comment by Stoatwblr** [comment]
Thanks! :)

**Comment by chichtacos** [comment]
Hi !

have you got any news on this topic ? 
It's just for information :)

Thx a lot !

**Comment by C-Duv** [comment]
You can try the [3.1.2-alpha release](https://github.com/pluginsGLPI/room/releases/tag/3.1.2-alpha).

**Comment by C-Duv** [comment]
I see plugin v3.1.2-alpha were downloaded and I see no new issue on GitHub: So I'll probably release the version (remove the *-alpha* label) this week-end.
Thanks to those who downloaded and tested it :)

**Comment by mrcssilvasouza** [comment]
Dear,

This version does not work without GLPI 9.3.2 and 9.3.3

**Comment by C-Duv** [comment]
> This version does not work without GLPI 9.3.2 and 9.3.3

Do you mean it does not works *with* v9.3.2 and v9.3.3?

I tested the [3.1.2-alpha release](https://github.com/pluginsGLPI/room/releases/tag/3.1.2-alpha) on v9.3.1 and it worked fine.

**Comment by Stoatwblr** [comment]
I think he means that it requires 9.3.2+ and won't work on earlier ones.

It works fine here

**Comment by C-Duv** [comment]
I only tested it on v9.3.1 (not 9.3.2 nor 9.3.3).

Also, since #30 plugin does not support anything prior to GLPI v9.1.
Released plugin version v3.1.1 should work on GLPI v9.2.x and plugin v3.1.0 on GLPI v0.85, v0.90 and v9.1.x.

**Comment by kornelson** [comment]
It works in glpi 9.3.3. I don't understand how to associate computers with this room. It can be possible?

**Comment by C-Duv** [comment]
Closing this issue since the 3.1.2 release works on GLPI 9.3.1

@kornelson See #38 for the future or your computer-room association problem (which I confirm is not currently possible).
