### ISSUE TITLE
9.3.1/3.1.2alpha: sql error reported:

### ISSUE THREAD

**Issue by Stoatwblr** [pluginsGLPI/room#35]
Installing works fine, but enabling shows this error:

[2019-01-24 13:22:40] glpisqllog.ERROR: DBmysql::query() in /usr/share/glpi/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: SELECT *
                             FROM `glpi_profilerights`
                             WHERE `profiles_id` 4
                                AND `name` LIKE "%plugin_room%"
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '4
                                AND `name` LIKE "%plugin_room%"' at line 3
  Backtrace :
  inc/dbmysqliterator.class.php:95                   
  inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
  plugins/room/inc/profile.class.php:195             DBmysql->request()
  inc/plugin.class.php:800                           PluginRoomProfile::initProfile()
  front/plugin.form.php:47                           Plugin->activate()
  {"user":"11@msslyz.mssl.ucl.ac.uk"}

**Comment by Stoatwblr** [comment]
It looks like inc/profile.class.php line 195 is missing a "=" character

-                WHERE `profiles_id`  ' . $_SESSION['glpiactiveprofile']['id'] . '
+               WHERE `profiles_id` = ' . $_SESSION['glpiactiveprofile']['id'] . '

**Comment by C-Duv** [comment]
Fixed, thanks @Stoatwblr.
