### ISSUE TITLE
Version GLPI 9.4.0 ou autre plugin

### ISSUE THREAD

**Issue by KaiserTroll** [pluginsGLPI/room#37]
Bonjour,

Je voulais savoir s'il existait une version de Room compatible avec GLPI 9.4.0 ?
Sinon, existe-t-il un plugin permettant de faire de la gestion de salle ?

D'avance merci
Cordialement,

**Comment by jackburton79** [comment]
I fixed the version check so the plugin could work with glpi 9.4 (I'm using it with 9.4.2 here, works fine, it seems).

I opened PR #39 to propose merging.

**Comment by C-Duv** [comment]
Closing in favor of #36.
