### ISSUE TITLE
Rooms disappeared

### ISSUE THREAD

**Issue by erald95** [pluginsGLPI/room#42]
When trying to `add` some more fields on `global view` all the rooms that i had disappeared but not deleted from the database. I checked and they are still there. There was no sing of any error, they just disappeared. 

GLPI 9.4.4
room 3.1.2

**Comment by n0rvik** [comment]
```
GLPI 9.4.5
room 3.1.2
```

```
function plugin_room_check_prerequisites()
{
    if (version_compare(GLPI_VERSION, '9.3.1', '>=') && version_compare(GLPI_VERSION, '9.4', '<')) {
        return true;
```

**Comment by jackburton79** [comment]
This version works also on 9.5 now
