### ISSUE TITLE
UPDATE for 9.5+

### ISSUE THREAD

**Issue by EunirCarolino** [pluginsGLPI/room#57]
Please! Update! Actual version doesnt work on glpi 9.5.5

**Comment by jackburton79** [comment]
Hi!
The released version does not work on glpi 9.5, indeed.
The code from master branch works, though.
You can get it by cloning the master branch of the git repository.

**Comment by AdrianXuizGarcia** [comment]
That branch of your repo should work on 9.5.5, then? Cos thats the one ive been trying to make it work... And gives the error I commented before :(

**Comment by jcervantes-sipecom** [comment]
Hi @jackburton79, I have downloaded and installed your version compatibility for 9.5, but there is a bug when uninstalled the plugin with a Room that have been activated a reservation, that cause a bug with another plugin, Reservation Plugin, please check this: https://github.com/salleman33/reservation/issues/64

**Comment by jackburton79** [comment]
Will have a look

**Comment by jackburton79** [comment]
I just pushed a change (on the glpi-10 branch) which should fix that problem.
BEWARE! I just tested it briefly on my test installation, I RECOMMEND YOU to try it in a test environment to avoid losing reservations

**Comment by jackburton79** [comment]
I also pushed on the 9.5 branch here: https://github.com/jackburton79/room/tree/glpi_9.5-fixes

**Comment by jackburton79** [comment]
Closing since there has been a release which works on 9.5
