### ISSUE TITLE
PHP Warning:  Invalid relations declared between "glpi_plugin_room_dropdown1s" and "glpi_plugin_room_rooms" table. Target field "dropdown1" is not a foreign key field

### ISSUE THREAD

**Issue by ftoledo** [pluginsGLPI/room#62]
I just update to glpi 10.0.7

PHP Warning:  Invalid relations declared between "glpi_plugin_room_dropdown1s" and "glpi_plugin_room_rooms" table. Target field "dropdown1" is not a foreign key field

**Comment by FlorianV54** [comment]
Good Afternoon,

We have same problem on our side. I opened an issue in the fork few weeks ago. https://github.com/jackburton79/room/issues/5

I hope we can have a feedback soon

**Comment by ftoledo** [comment]
> Good Afternoon,
> 
> We have same problem on our side. I opened an issue in the fork few weeks ago. [jackburton79#5](https://github.com/jackburton79/room/issues/5)
> 
> I hope we can have a feedback soon

excelent i have exactly issue!

**Comment by ftoledo** [comment]
Duplicate of jackburton79#5
